-- 코드를 입력하세요
/*
동일한 회원이 동일한 상품: 한 USER_ID-PRODUCT_ID쌍이 테이블 내에 여러 행 존재
*/
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(PRODUCT_ID) >= 2
ORDER BY USER_ID, PRODUCT_ID DESC