-- 코드를 입력하세요
WITH a AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
    GROUP BY CAR_ID
)
SELECT b.CAR_ID, IF(a.CAR_ID = b.CAR_ID, '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
LEFT JOIN a USING(CAR_ID)
GROUP BY b.CAR_ID
ORDER BY b.CAR_ID DESC