-- 코드를 입력하세요
SELECT fp.PRODUCT_ID, 
    fp.PRODUCT_NAME, 
    SUM(fo.AMOUNT * fp.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo USING (PRODUCT_ID)
WHERE YEAR(fo.PRODUCE_DATE) = '2022'
    AND MONTH(fo.PRODUCE_DATE) = '5'
GROUP BY fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID
;