-- 코드를 입력하세요
SELECT DISTINCT car.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history USING (CAR_ID)
WHERE car.CAR_TYPE = '세단'
    AND MONTH(history.START_DATE) = 10
ORDER BY car.CAR_ID DESC
;