-- 코드를 입력하세요
SELECT
    b.CATEGORY AS CATEGORY
    , SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES bs USING (BOOK_ID)
WHERE
    YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 1
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;